### ISSUE TITLE
Use unsafeWindow in setTimeout callback throw an error

### ISSUE THREAD

**Issue by yume-chan** [scriptish/scriptish#91] opened 2013-04-12 19:22 UTC
Just use the following code

``` javascript
setTimeout(function() { unsafeWindow.document }, 200);
```

Then Firefox show this error
`Illegal operation on WrappedNative prototype object`
My friend told me that codes like this works on GreaseMonkey.

Firefox nightly 23.0a1 + Scriptish 0.1.8

**Comment by kmod-midori** [comment] 2013-04-13 14:31
This code works on Tampermonkey with Google Chrome 26.0.1410.43 m.

**Comment by ghost** [comment] 2013-04-14 21:49
Try `window.setTimeout` instead of just `setTimeout`. I opened a bug report for this here: https://github.com/scriptish/scriptish/issues/89

**Comment by yume-chan** [comment] 2013-04-26 22:53
@kuehlschrank Yes it should be same bug.

**Comment by erikvold** [comment] 2013-04-27 06:44
duplicate of #89

**Closed as completed by erikvold** 2013-04-27 06:44 UTC
