### ISSUE TITLE
Script update fails with scriptish

### ISSUE THREAD

**Issue by Owyn** [scriptish/scriptish#205] opened 2014-03-14 17:57 UTC
Script update fails with scriptish. Works fine with GreaseMonkey and TamperMonkey.
http://userscripts.org/scripts/source/166494.user.js - script
http://userscripts.org/topics/208709?page=1#posts-609163 - problem

**Comment by alexolog** [comment] 2014-03-17 15:19
The problem manifests itself with the Handy Just Image script (https://userscripts.org/scripts/show/166494)

1) Scriptish always thinks that an update is available, even immediately after reinstalling the latest version.

2) Trying to update, results in "There was an error downloading Handy Image" error message.

**Comment by alexolog** [comment] 2014-03-17 15:34
Seems to be duplicate of #186

**Comment by erikvold** [comment] 2021-06-24 01:55
I'm going to archive the repo soon.

**Closed as completed by erikvold** 2021-06-24 01:55 UTC
Labels: BUG
