### ISSUE TITLE
[Help] Can't GM_getResourceText from @resource     

### ISSUE THREAD

**Issue by Killika** [scriptish/scriptish#208] opened 2014-03-24 01:19 UTC
Hi, I'm new to Scriptish, I have a problem and maybe I can ask here?

I tried the example in https://github.com/scriptish/scriptish/wiki/GM_getResourceText
// ==UserScript==
// @name         GM_getResourceText test
// @namespace    myCoolNamespace
// @include      *
// @resource     myDoc http://www.mywebsite.com/myDoc.txt
// ==/UserScript==
GM_log("text contents of myDoc: " + GM_getResourceText("myDoc"));

but console log only says:
"[GM_getResourceTexttest]" "text contents of myDoc: undefined"
I tried @grant GM_getResourceText, change myDoc.txt to my website address, creat new Firefox profile with only Scriptish, but nothing changed.

p/s: I'm using win 7, Firefox Aurora 30.0a2, and above code works fine with Greasemonkey

**Comment by Tyf0x** [comment] 2014-03-31 01:45
+1, same problem here. (Only difference is that I import a local file: @resource zones zones.xml)

**Comment by LouCypher** [comment] 2014-03-31 02:52
Dupe of #203.

**Comment by brunoais** [comment] 2014-10-21 07:48
I get this sometimes. In my case, it is a local file. What's wrong?!?!

**Comment by erikvold** [comment] 2021-06-24 01:54
I'm going to archive the repo soon.

**Closed as completed by erikvold** 2021-06-24 01:54 UTC
